FROM public.ecr.aws/lambda/python:3.12

COPY ./requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install --no-cache-dir -r requirements.txt

COPY cost_report_Unicloud.py ${LAMBDA_TASK_ROOT}
RUN ls
RUN pwd
RUN echo $PWD
EXPOSE 8080
CMD ["cost_report_external_account.lambda_handler"]